# Generated by Django 3.1.4 on 2021-01-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
